#' Returns cosine cosimilarity matrix for the terms generated by conclust
#'
#' @description A function that extracts the cosimilarity matrix for
#' terms generated by [conclust()]
#' @param x output from [conclust()]
#' @keywords conclust
#' @export
cosimilarity_matrix <- function(x) {
    UseMethod("cosimilarity_matrix")
}

#' @export
cosimilarity_matrix.conclust <- function(x) {
    return(x$Cosim_mat)
}

