#' Returns cosine cosimilarity matrix for the terms generated by keyclust
#'
#' @description A function that extracts the cosimilarity matrix for
#' terms generated by [keyclust()]
#' @param x output from [keyclust()]
#' @keywords keyclust
#' @export
cosimilarity_matrix <- function(x) {
    UseMethod("cosimilarity_matrix")
}

#' @export
cosimilarity_matrix.keyclust <- function(x) {
    return(x$Cosim_mat)
}

